language: node_js
node_js:
  - "0.10"
before_install: npm install -g grunt-cli

notifications:
  email:
    recipients:
      - fleur@obscure.org
      - stacy.hseu@gmail.com
      - brandonpmcnary@gmail.com
      - s.benjamin.nelson@gmail.com
    on_success: change
    on_failure: change

